// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3h42Wqw3bldYW9u75-WIbbkOxjr0SOwg',
    appId: '1:494264802419:web:98f849ec09b7209e2e1e06',
    messagingSenderId: '494264802419',
    projectId: 'merecruapp',
    authDomain: 'merecruapp.firebaseapp.com',
    storageBucket: 'merecruapp.appspot.com',
    measurementId: 'G-XC4TGK7TX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCWGFce22i5ulR1OVCq9Y9QdhkcVuMUl0',
    appId: '1:494264802419:android:12e9dd52f17a24722e1e06',
    messagingSenderId: '494264802419',
    projectId: 'merecruapp',
    storageBucket: 'merecruapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFu_JC2OSRhyWU7zJ6hq4C7A5AyFLfj3M',
    appId: '1:494264802419:ios:383bb695db7f0f7c2e1e06',
    messagingSenderId: '494264802419',
    projectId: 'merecruapp',
    storageBucket: 'merecruapp.appspot.com',
    iosClientId: '494264802419-8aokv1rc4vvfgljaqdoa04uahjlva2nj.apps.googleusercontent.com',
    iosBundleId: 'com.example.meRecruApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFu_JC2OSRhyWU7zJ6hq4C7A5AyFLfj3M',
    appId: '1:494264802419:ios:383bb695db7f0f7c2e1e06',
    messagingSenderId: '494264802419',
    projectId: 'merecruapp',
    storageBucket: 'merecruapp.appspot.com',
    iosClientId: '494264802419-8aokv1rc4vvfgljaqdoa04uahjlva2nj.apps.googleusercontent.com',
    iosBundleId: 'com.example.meRecruApp',
  );
}
